# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-01 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('unit', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=50)),
                ('img1', models.CharField(max_length=256)),
                ('img2', models.CharField(max_length=256)),
                ('img3', models.CharField(max_length=256)),
                ('img4', models.CharField(max_length=256)),
                ('img5', models.CharField(max_length=256)),
                ('img6', models.CharField(max_length=256)),
                ('img7', models.CharField(max_length=256)),
                ('img8', models.CharField(max_length=256)),
                ('img9', models.CharField(max_length=256)),
                ('img10', models.CharField(max_length=256)),
            ],
        ),
    ]
