# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-10 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_lunbo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunbo',
            name='trackid',
            field=models.IntegerField(default=0),
        ),
    ]
